# Generated by Django 5.0.1 on 2024-01-15 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capacity', models.SmallIntegerField(default=6)),
                ('lobby_name', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField(auto_now_add=True)),
                ('piece', models.CharField(choices=[('pawn', 'PAWN'), ('bishop', 'BISHOP'), ('knight', 'KNIGHT'), ('rook', 'ROOK'), ('queen', 'QUEEN'), ('king', 'KING')], default='pawn', max_length=6)),
                ('color', models.CharField(choices=[('white', 'WHITE'), ('black', 'BLACK')], default='white', max_length=5)),
                ('move', models.CharField(max_length=16)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess.board')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('player', models.CharField(default='', max_length=16)),
                ('wins', models.IntegerField()),
                ('ingame', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='chess.lobby')),
            ],
        ),
    ]
